apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: daily-all-sources
  namespace: argo
spec:
  schedules:
    - "0 2 * * *"
  timezone: "Europe/Madrid"
  concurrencyPolicy: Forbid
  workflowSpec:
    workflowTemplateRef:
      name: ingest-all-sources