apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opensky-credentials
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameterstore
  target:
    name: opensky-credentials
    creationPolicy: Owner
  data:
    - secretKey: OPENSKY_CLIENT_ID
      remoteRef:
        key: /data-platform/prod/opensky/client-id
    - secretKey: OPENSKY_CLIENT_SECRET
      remoteRef:
        key: /data-platform/prod/opensky/client-secret
