apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ingest-traffic-dag-
spec:
  serviceAccountName: workflow
  entrypoint: ingest-traffic-dag
  templates:
    - name: ingest-traffic-dag
      dag:
        tasks:
          - name: ingest
            template: ingest
          - name: validate
            template: validate
            dependencies: [ingest]
            continueOn:
              failed: true  
            arguments:
              parameters:
                - name: object_key
                  value: "{{tasks.ingest.outputs.parameters.object_key}}"
          - name: notify
            template: notify
            dependencies: [validate]
            when: "{{tasks.validate.status}} == Failed"
    
    - name: ingest
      outputs:
        parameters:
          - name: object_key
            valueFrom:
              path: /tmp/object_key.txt
      container:
        env:
          - name: CENTER_ID
            value: "EUR_MAD_001"
          - name: SIMULATION_API_URL
            value: "http://simulation-api:8000"
          - name: MINIO_ENDPOINT
            value: "http://minio:9000"
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: access_key
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: secret_key
        image: python-ingestor:local
        imagePullPolicy: Never
        command: [python]
        args: [ingest.py]
      
    - name: validate
      inputs:
        parameters:
          - name: object_key
      container: 
        env:
          - name: OBJECT_KEY
            value: "{{inputs.parameters.object_key}}"
          - name: BUCKET
            value: "raw"
          - name: EXPECTED_RECORDS
            value: "7"
          - name: MINIO_ENDPOINT
            value: "http://minio:9000"
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: access_key
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: secret_key
        image: data-quality:local
        imagePullPolicy: Never
        command: [python]
        args: [validate.py]
    - name: notify
      container:
        image: alpine:3.18
        command: [echo]
        args: ["validation failed — check logs"]